### ISSUE TITLE
Tags not right-aligned anymore

### ISSUE THREAD

**Issue by llcc** [amake/orgro#118]
![image](https://github.com/user-attachments/assets/0285369d-6ff7-4a31-a0bc-f41adda0b895)

**Comment by amake** [comment]
Yes, that is intended because

- You are not using Reader Mode, and
- Your screen width cannot fit the tags without wrapping

If you want the tags right-aligned you can

- Use Reader Mode
- Fit more text horizontally by e.g.
  - Using the full screen width (the third icon from the right on the top bar)
  - Reducing the font size
  - Putting your device in landscape orientation

**Comment by llcc** [comment]
Got it. Thanks. I'm closing this issue now.
