### ISSUE TITLE
Add more fonts with good Unicode coverage

### ISSUE THREAD

**Issue by oatmealm** [amake/orgro#20]
It seems like there's only one font used to cover non Latin scripts? When opening files contains text in Hebrew it seems to be possible to only use one font. Also, the fonts is sans serif, which great for heading but not so much for body text.

**Comment by amake** [comment]
Orgro lets you select a font to use as the "primary" font (from a selection of monospaced fonts from Google Fonts) but characters not covered by that font will fall back to whatever the OS provides. 

For instance you can see in the Supported Features > Tables section of the manual there is some Japanese text in the table; I don't believe any of the Google Fonts monospace fonts cover Japanese, so that is falling through to the OS's font. 

I will see if I can influence the font family type chosen as fallback (e.g. on the level of mono vs serif vs sans), but I won't be doing these:

- Embed script-specific fonts
- Specify script-specific font families

**Comment by amake** [comment]
Also right now I only offer monospaced fonts because there are just too many fonts in Google Fonts. If Google Fonts offers a better font for your use case, please let me know and I can think about adding that. 

(Google Fonts are downloaded dynamically, so it doesn't bloat the app binary.)

**Comment by oatmealm** [comment]
> If Google Fonts offers a better font for your use case, please let me know and I can think about adding that. 

I'm not sure, but I think that in Linux a good **proportional** font that has good Unicode coverage and is often used for documents is Liberation... there's also Google's Noto family that's broken down by script... including Hebrew, Arabic and almost anything else. 

I understand monospace as a choice for org, but the fact that it's not serif is sort of painful in Hebrew at least. 

Regardless, it's so wonderful to be able to easily display my org notes on my iPhone and iPad for study etc. 👍

**Comment by amake** [comment]
I should have been more clear: Google Fonts offers a package for Flutter that allows dynamically downloading and applying (almost) any of the fonts here:
https://fonts.google.com/

I don't want to bundle any actual fonts because

1. They bloat the app's binary size
2. There's no one-size-fits-all choice

So for instance I won't offer Liberation because it's not offered on Google Fonts.

The versions of Noto on Google Fonts [don't appear to support Hebrew](https://fonts.google.com/?preview.text=%D7%A2%D6%B4%D7%91%D6%B0%D7%A8%D6%B4%D7%99%D7%AA%E2%80%8E&preview.text_type=custom&query=noto).

There are, however, [several Hebrew-supporting fonts available](https://fonts.google.com/?subset=hebrew).

Feel free to look through them and give me the name of one or two (say, a serif and a sans) and I can include those.

(The reason I don't simply offer *every* Google Fonts font is, as I mentioned before, because there are just too many to choose from, and I don't want to make a really specialized UI just for selecting the font.)

**Comment by oatmealm** [comment]
Yes. Understood. 

Looking at google fonts, it doesn't offer many of the fonts that are installable on Linux, where you can find repackaged Noto Sans Hebrew, Noto Sans Arabic etc. 

Also, looking at their selection of Hebrew fonts, it doesn't even include the most popular free font collection "Culmus"... so I'm not sure. 

There are iOS apps by the way, like Texpad, that offer selective download of components and fonts. I guess they're  reusing some existing TeX distro for this, but it also means they have more control. I don't know if it's something you have the bandwidth to deal with (in term of your time).

**Comment by oatmealm** [comment]
FiraGO

BTW I came across this variable pitch variant of Fira. Seems to be sans but with good basic Unicode coverage. 

>> Based on the Fira Sans 4.3 glyph set, FiraGO now supports Arabic, Devanagari, Georgian, Hebrew and Thai. With this script support, FiraGO catches up with other globally extended and free typefaces such as Noto.

https://bboxtype.com/typefaces/FiraGO

**Comment by amake** [comment]
Fira Go looks nice, but it's not on Google Fonts, and I don't think it's appropriate for bundling in the app itself (as a proportional font I don't think it's what most people, myself included, would want by default).

I will see if it's feasible to implement dynamic loading like the Google Fonts Flutter package does, but if not then I'm going to have to say no to anything

- not in Google Fonts, or
- not appropriate to be the single default bundled font (which is currently Fira Code)

**Comment by amake** [comment]
I had to make [a whole package](https://github.com/amake/dynamic-fonts-flutter) to do it, but I added dynamic loading of FiraGO.

I just submitted the build to [TestFlight](https://testflight.apple.com/join/8YTxcuZC), so please let me know if this meets your needs.

**Comment by oatmealm** [comment]
> I had to make [a whole package](https://github.com/amake/dynamic-fonts-flutter) to do it, but I added dynamic loading of FiraGO.

Hi! I've installed it and I can see Fira code and mono, but not firago...

**Comment by amake** [comment]
The TestFlight build (1.7.0) is still in review. You'll get a notification when it's available.

**Comment by amake** [comment]
The build is now on TestFlight.

**Comment by oatmealm** [comment]
Looks great! Thanks a lot.

**Comment by amake** [comment]
Are you satisfied with FiraGO enough that we can close the ticket?

**Comment by oatmealm** [comment]
> Are you satisfied with FiraGO enough that we can close the ticket?

Yes. It's good. Thank you!
