### ISSUE TITLE
Do not wrap clock lines

### ISSUE THREAD

**Issue by psamim** [amake/orgro#31]
Hi!

I see that table lines are not wrapped. I'm going to suggest the same for drawers. Here you can see clock drawer lines being wrapped which makes them unreadable and ugly. I'm not sure if it makes sense or not.

![Screenshot_20210222-170430_Orgro](https://user-images.githubusercontent.com/1868679/108715406-1409d200-7530-11eb-9eb6-f356703222ad.jpg)

Thanks!

**Comment by amake** [comment]
I suppose that drawer content tends to be line-oriented stuff that doesn't make a lot of sense to wrap. I will try giving it the same scrolling treatment as tables and blocks, and if it doesn't seem weird then I'll release it.

**Comment by amake** [comment]
In principle you can put anything in a drawer, including things that *should* wrap, so I'm not so sure about always scrolling the drawer. Doing so also creates implementation difficulties due to how Flutter widget layout works.

Instead I think making individual `CLOCK:` lines and `:property: value` lines scroll horizontally would mostly be adequate.

**Comment by psamim** [comment]
@amake Thanks, it makes sense. Although personally I use no drawer which needs wrapping.

**Comment by amake** [comment]
This is addressed in v1.15.0. Test builds will be available shortly:
- [Android](https://play.google.com/apps/testing/com.madlonkay.orgro)
- [iOS](https://testflight.apple.com/join/8YTxcuZC)

**Comment by psamim** [comment]
Thanks! I just updated to v1.15.0 and it works flawlessly.
