### ISSUE TITLE
[Feature request] Dropbox connectivity directory

### ISSUE THREAD

**Issue by wakatara** [amake/orgro#4]
This looks exciting. Thanks for working on this.

However, for it to be truly useful for me, I really need it to have connectivity to Dropbox in order to take advantage of being able to use it for my large Deft and org-roam directories. Any chance of being able to include that (as well, as... and I know you've probably heard this already) editing?... =p. (though was surprised to see it support Apple's native files when I purchased... =] ).

[BeOrg](https://beorgapp.com) breakthrough with users I imagine came through when he provided Dropbox connectivity since so many real emacs users use that for sync directories (possibly in addition to secure webdav).

Really excited and heartened to see more people working on cross platform apps for org-mode.

**Comment by amake** [comment]
Thanks very much for your purchase, and for your request.

As you know, Orgro already works with the OS files API. This means that you should already have access to your Dropbox files via the Open File button:

1. Tap Open File
2. Tap the Browse tab
3. If you're not at the root Browse screen (I think usually you're not by default), tap the upper left button that takes you up in the hierarchy
4. If Dropbox isn't in the list of Locations, tap the upper right menu button (circled `...`) then tap Edit
5. Enable Dropbox and tap Done
6. Choose Dropbox from the Locations list

![orgro-dropbox](https://user-images.githubusercontent.com/2172537/83947115-07353900-a850-11ea-9f54-984e6382caaa.gif)

Is there anything you could do with "full" Dropbox support (via their SDK, I imagine) that you can't do with the existing functionality?

Note also that in an upcoming release (very soon, hopefully), Orgro will be able to remember and provide quick access to recently opened files, including those in Dropbox, so you won't have to go through the file picker every time.

**Comment by wakatara** [comment]
Hehe... I have to admit embarrassment and that I owe you an apology for not realizing I could access Dropbox files via the Apple Files native functionality (also, bonus points for the video!! Wow. Bonus points for extreme support.).

In Beorg, the functionality is a direct config option so I had assumed the same was required for orgro (I think you should rename it ogre btw... =] ).

This works fine this way. Thank you for the pointer. I have to admit however, that Dropbox direct sycns seem to work better than Apple Files syncing capabilities. I've had loads of litlte issues with files not syncing properly so may be something to watch out for in the future, though this definitely works. 

(still, editing files in org mode on the go would be the bomb for me here though again, with te above that might be affected by how files sync.).

thanks!

**Comment by amake** [comment]
> I have to admit embarrassment and that I owe you an apology for not realizing I could access Dropbox files via the Apple Files native functionality

It is well hidden! The Files app is very dense and, in my opinion, hard to use.

> In Beorg, the functionality is a direct config option

Beorg specifically treats Dropbox as a privileged data source, and requires you to give it direct access via Dropbox’s API. I actually prefer not to privilege any one provider or include their (non-free) SDK, partly on principle, and partly because it’s a lot of work for something I probably don’t need myself. 

But I am not against it if doing so enables compelling new functionality that can’t be implemented any other way.

> I think you should rename it ogre btw... =]

I like that! If I had thought of it I might have. At this point I like the logo too much to give it up, and it would be very odd to be named “ogre” but have a unicorn icon.

> I've had loads of litlte issues with files not syncing properly

That’s frustrating. I’ll keep my eyes peeled for any issues and see if there’s anything to be done about it in Orgro.

> editing files in org mode on the go would be the bomb for me

Editing would be a very big stretch goal. File access I don’t think is the main hurdle. Off the top of my head the main barriers are:

- Medium difficultly: Ensuring faithful round-trip from text to parsed representations and back to text. I wouldn’t want to mangle files or make spurious changes, but I didn’t design the parser with round-tripping in mind, so that might be hard.
- Very hard difficulty: Making a good interface for editing. The display is not one big text buffer with styling like in Emacs, it’s a bunch of separate UI components (“widgets” in Flutter parlance). So editing can’t be as simple as placing a cursor and typing, which is probably not very desirable on mobile anyway. It will be hard just to design a usable interface; implementing it may be even harder—it could require completely reimplementing the current UI.

That said, I may get the itch to do something a bit smaller in scope, such as allowing checking checkboxes or toggling todo status.

Anyway, thanks for the feedback!

**Comment by mpereira** [comment]
Hi @amake,

Thanks for creating this app. I just bought it and it looks great and seems to work well.

I'm on Android, and realized that there's no support for opening Dropbox files. Is this something you intend on implementing any time soon?

**Comment by amake** [comment]
@mpereira Thanks very much for your purchase.

Regarding Dropbox on Android, please see [the FAQ](https://orgro.org/faq/#can-orgro-sync-with-dropbox). The fact that Dropbox doesn't show up in the file picker is a choice made by Dropbox, and only they can remedy it.

You can open Dropbox files in Orgro *from within the Dropbox app* by the usual means: select Orgro from the "Open with" dialog.
![Screenshot (Sep 3, 2020 09:00:05)](https://user-images.githubusercontent.com/2172537/92048979-03b83c00-edc4-11ea-89d3-c7a8e43e0eb7.png)


The only other option would be to incorporate the Dropbox SDK and make you authorize Orgro to access your account. I won't be doing that for a number of reasons.

**Comment by mpereira** [comment]
Hi @amake,

Thanks for the reply. I guess I understand not wanting to implement the Dropbox SDK into orgro.

You probably already realize this, but as feedback, this makes the app less convenient than alternatives like [organice](https://github.com/200ok-ch/organice). From my POV as a user, having to open org files from Dropbox is cumbersome.

Anyway, thanks again for the app!
