### ISSUE TITLE
Section title not parsed correctly

### ISSUE THREAD

**Issue by gety9** [amake/orgro#75]
Usually orgro works good for my notes, however there is one note which is not displayed correctly. Several headings are merged.

Here is how note should look like
![Screenshot_20230605-193818](https://github.com/amake/orgro/assets/16415882/74c21f3e-5ae7-4ec5-9c70-43e0eb1c693b)
Here is how it looks in orgro
![Screenshot_20230605-193728](https://github.com/amake/orgro/assets/16415882/c93d4262-cf5f-42d1-b1dc-c238d212a3cd)

Something breaks starting from line number 267 (line "***** Aaa 2022 Aaaaaaa $10a")
How it should look like
![Screenshot_2023-06-05_19-38-02](https://github.com/amake/orgro/assets/16415882/cd7518ef-fe62-4cfc-b050-f53a46d8460e)
How it looks
![Screenshot_20230605-193712](https://github.com/amake/orgro/assets/16415882/23a83798-a567-49cc-8fe1-6364be8e15c3)

Here is "code" of the note:
https://codefile.io/f/T4HAARcWkE

(to protect privacy i changed all letters to Aa so i could share screenshots & "code")

**Comment by amake** [comment]
Thank you for the report. This is a bug in the parser. A minimal sample that reproduces the issue is this document:

```org
* A $1
* B
1$
```

The parser thinks the region between the `$`s is an inline LaTeX block. I will see about fixing this.

**Comment by gety9** [comment]
@amake Aaron, will it be available on Fdroid? (last time you needed to create some kind of request...)

**Comment by amake** [comment]
I hadn't released 1.28.3 because I was waiting for feedback. F-Droid doesn't support prereleases so I usually do it last.

I haven't heard of any problems so far with 1.28.3. If you're unable to test without the F-Droid release then I will release 1.28.3 on all platforms.

> (last time you needed to create some kind of request...)

With the last version I changed it so that I no longer need to open merge requests for new versions. However F-Droid seems quite slow about putting out new builds, so it may be several days.

**Comment by gety9** [comment]
@amake Aaron, thank you, all is good now (on 1.28.3)
closing the issue.
